# models.py
"""
Pydantic schemas for the transcription pipeline.

WHY THIS FILE EXISTS:
    Every module in MediFlow should have typed inputs and outputs.
    Instead of passing raw dicts or strings between functions, we use
    Pydantic models so that:
    1. Every field is validated automatically.
    2. The API response schema is auto-generated by FastAPI.
    3. Downstream modules (SOAP note generator) receive a predictable shape.
"""
from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime


class TranscriptSegment(BaseModel):
    """
    A single time-stamped segment from the transcription.

    WHY SEGMENTS:
        Whisper naturally produces segment-level output (chunks of ~30s).
        Keeping segments lets us:
        - Show timestamps to the doctor for review
        - Allow editing of specific parts
        - Map segments to SOAP note sections later
    """
    start: float = Field(description="Start time in seconds")
    end:   float = Field(description="End time in seconds")
    text:  str   = Field(description="Transcribed text for this segment")


class TranscriptionResult(BaseModel):
    """
    Complete result of a transcription job.

    This is the OUTPUT of the transcription pipeline and the
    INPUT to Module 2 (Transcript Structuring / SOAP notes).
    """
    # Core output
    full_text:  str                   = Field(description="Full transcript as a single string")
    segments:   List[TranscriptSegment] = Field(description="Time-stamped segments")

    # Metadata
    audio_file:     str                = Field(description="Original uploaded filename")
    duration_secs:  float              = Field(description="Audio duration in seconds")
    language:       str                = Field(default="en", description="Detected language")
    model_used:     str                = Field(description="Whisper model name used")

    # Timestamps
    created_at:     datetime           = Field(default_factory=datetime.now)
    processing_ms:  Optional[float]    = Field(default=None, description="Transcription time in ms")
